services:
  edubox_fixtures:
    class: EduBoxBundle\DataFixtures\EduBoxFixtures
    $kernelRootDir:  '%kernel.root_dir%'

  edubox_admin_resource:
    class: EduBoxBundle\Admin\ResourceAdmin
    arguments: [~, EduBoxBundle\Entity\Resource, ~]
    tags:
      - name: sonata.admin
        manager_type: orm
        label: 'Maglumatlar'
        group: 'Maglumatlar'
        icon: '<i class="fa fa-bookmark"></i>'
        on_top: true

  edubox_admin_book:
    class: EduBoxBundle\Admin\BookAdmin
    arguments: [~, EduBoxBundle\Entity\Book, ~]
    tags:
      - name: sonata.admin
        manager_type: orm
        label: 'Kitaplar'
        group: 'Kitaplar'
        icon: '<i class="fa fa-book"></i>'
        on_top: true

  edubox_admin_author:
    class: EduBoxBundle\Admin\AuthorAdmin
    arguments: [~, EduBoxBundle\Entity\Author, ~]
    tags:
      - name: sonata.admin
        manager_type: orm
        label_translator_strategy: sonata.admin.label.strategy.form_component
        label_catalogue: 'EduBoxBundle'
        label: 'Awtorlar'
        group: 'Awtorlar'
        icon: '<i class="fa fa-users"></i>'
        on_top: true

  edubox_admin_problem:
    class: EduBoxBundle\Admin\ProblemAdmin
    arguments: [~, EduBoxBundle\Entity\Problem, ~]
    tags:
      - name: sonata.admin
        manager_type: orm
        label: 'Meseleler'
        group: 'Meseleler'
        icon: '<i class="fa fa-cube"></i>'
        on_top: true

  edubox_admin_problem_test:
    class: EduBoxBundle\Admin\ProblemTestAdmin
    arguments: [~, EduBoxBundle\Entity\ProblemTest, ~]
    tags:
      - name: sonata.admin
        manager_type: orm
        show_in_dashboard: false

  edubox_submission_manager:
    class: EduBoxBundle\DomainManager\SubmissionManager
    arguments: ['@doctrine.orm.entity_manager']

  edubox_book_manager:
    class: EduBoxBundle\DomainManager\BookManager
    arguments: ['@doctrine.orm.entity_manager', '@kernel', '@router']

  edubox_author_manager:
    class: EduBoxBundle\DomainManager\AuthorManager
    arguments: ['@doctrine.orm.entity_manager']

  edubox_resource_manager:
    class: EduBoxBundle\DomainManager\ResourceManager
    arguments: ['@doctrine.orm.entity_manager']

  edubox_problem_manager:
    class: EduBoxBundle\DomainManager\ProblemManager
    arguments: ['@doctrine.orm.entity_manager']

  edubox_code_submit_handler:
    class: EduBoxBundle\Form\CodeSubmitHandler
    arguments: ['@edubox_submission_manager']