<?php

namespace EduBoxBundle\Repository;

/**
 * ProblemCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
