<?php

namespace EduBoxBundle\Repository;

/**
 * ProblemInOutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProblemTestRepository extends \Doctrine\ORM\EntityRepository
{
}
